services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data¨
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  bookapi:
    container_name: book-api
    build:
      context: ./BookApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnectionString=Host=postgres;Port=5432;Username=postgres;Password=password;Database=bookdb
    ports:
      - 8080:8080
    depends_on:
      - postgres

  bookapp:
    container_name: book-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: "http://localhost:8080"
    ports:
      - 1234:3000

volumes:
  pgdata:
